#!/bin/bash
#PBS -N c6h6_qz_6p00A
#PBS -l select=1:ncpus=32:mpiprocs=32:mem=172gb
#PBS -l walltime=25:00:00
#PBS -j oe
set -euo pipefail
cd /rds/general/user/ah1123/ephemeral/Angel/ORCA_scripts/cc-pVQZ/benzene_dimer_parallel_6p00A
module load OpenMPI/4.1.6-GCC-13.2.0
module load ORCA/6.1.0-gompi-2023b-avx2
/sw-eb/software/ORCA/6.1.0-gompi-2023b-avx2/bin/orca benzene_dimer_parallel_6p00A_qz.inp > benzene_dimer_parallel_6p00A_qz.out

